# Generated by Django 5.1.4 on 2025-01-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='street_category',
            old_name='dish',
            new_name='street',
        ),
    ]
