# Generated by Django 5.1.4 on 2025-02-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice_app', '0002_rename_dish_street_category_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_category',
            name='dish',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='event_category',
            name='event',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='street_category',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='table_category',
            name='number',
            field=models.CharField(max_length=7),
        ),
    ]
