# Generated by Django 5.1.4 on 2025-02-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice_app', '0003_alter_dish_category_dish_alter_event_category_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_category',
            name='number',
            field=models.CharField(max_length=5),
        ),
    ]
