# Generated by Django 5.1.4 on 2025-02-03 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('choice_app', '0004_alter_table_category_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('choice_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice_app.event_category')),
                ('choice_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice_app.table_category')),
            ],
        ),
    ]
