# Generated by Django 5.1.4 on 2025-02-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_alter_booking_table_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
