# Generated by Django 5.1.4 on 2025-01-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_order_app', '0002_orderitem_resultsolution_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsolution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
