# Generated by Django 5.1.4 on 2025-01-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('choice', models.CharField(max_length=200)),
                ('gram', models.CharField(max_length=4)),
                ('price', models.CharField(max_length=4)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_for_food_media/')),
            ],
        ),
    ]
