# Generated by Django 5.1.4 on 2025-01-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='gram',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
