# Generated by Django 5.1.4 on 2025-01-22 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice_app', '0002_rename_dish_street_category_street'),
        ('menu_app', '0003_alter_dishes_gram_alter_dishes_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='choice_app.dish_category'),
        ),
    ]
