# Generated by Django 5.1.4 on 2025-06-11 08:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_alter_dishes_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='photos_for_food_media/'),
        ),
    ]
